### ISSUE TITLE
FIT courses lead to internal system pages

### ISSUE THREAD

**Issue by tpetricek** [prgprg-org/prgprg-org.github.io#2]
All the current FIT courses take you to a page that asks you to log in and does not show anything.
After googling a bit, I guess a better link for them would be something like this:

https://bilakniha.cvut.cz/en/predmet6114506.html

@fikovnik @jaklt @programLyrique Can one of you locate the right publicly accessible links?

**EDIT**: It may be also useful to show the language in which the courses are taught. I added the data for my courses: e5736532be4c49f0931eba79cb6622d801ca40aa - it is not used anywhere yet (I can add that at some point) - but could you also add this to FIT courses?

**Comment by fikovnik** [comment]
Good catch! I updated the annotation and syllabus for I have no idea how that is converted into the white book.
Anyway better stalled data than nothing so I fixed my links in ee840b1daa0e75042a42648d20c99c65f394228e.

**Comment by jaklt** [comment]
Maybe better to use these slightly more modern pages?

- https://bilakniha.cvut.cz/en/predmet6082106.html#gsc.tab=0
- https://bilakniha.cvut.cz/cs/predmet6706506.html#gsc.tab=0

**Comment by fikovnik** [comment]
I was considering that, but they don't even have the name of the lecturers.

**Comment by jaklt** [comment]
Strangely, https://bk.fit.cvut.cz/en/predmety/00/00/00/00/00/00/03/46/12/p3461206.html doesn't have them for PPA but https://bilakniha.cvut.cz/cs/predmet6706506.html#gsc.tab=0 has them... So we probably use different pages, depending on the course.

**Comment by programLyrique** [comment]
I also changed the link for my course. I think we do not have internal links anymore.

**Comment by tpetricek** [comment]
I think we need to pick one of the links from @jaklt for the PPAs course.
